[name]
name = "Bar"
category = "Apps"
wifi_preference = false

[entry]
class = "BarApp"

[metadata]
author = "jake-walker"
license = "Unlicense"
url = "https://github.com/jake-walker/tildagon-bar-app"
description = "An app for browsing drinks available at the bars."
version = "0.0.2"
